---
- name: Install OpenSpec Training
  hosts: all
  gather_facts: true
  any_errors_fatal: true
  vars:
  tasks:
    - name: Disable SELinux
      tags: execute
      become: true
      ansible.posix.selinux:
        state: disabled

    - name: Install needed packages
      tags: execute
      become: true
      ansible.builtin.command: sudo dnf install -y unzip chromium git time bc gedit net-tools pip xorg-x11-xauth java-25-openjdk-devel.x86_64 maven node python3-setuptools

    - name: Install python dependencies
      tags: execute
      ansible.builtin.pip:
        name:
          - docker # Needed by docker_container

    - name: Create directories
      tags: execute
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - bin
        - Downloads
        - webtop/Desktop
        - webtop/.config

    - name: Ensure group docker exists
      tags: execute
      become: true
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add the user to docker group
      tags: execute
      become: true
      ansible.builtin.user:
        name: "{{ linux_user }}"
        groups: docker
        append: true

    - name: Install docker
      tags: execute
      become: true
      ansible.builtin.shell: dnf install -y docker

    - name: Start and enable docker
      tags: execute
      become: true
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Generate SSH key
      tags: execute
      community.crypto.openssh_keypair:
        path: "~/.ssh/id_rsa"
        type: rsa

    - name: Allow local user to login
      tags: execute
      ansible.posix.authorized_key:
        user: "{{ linux_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Fetch the keyfile from remote server
      tags: execute
      ansible.builtin.fetch:
        src: "~/.ssh/id_rsa.pub"
        dest: "/tmp/remote-{{ inventory_hostname }}-id_rsa.pub"
        flat: true

    - name: Allow remote user to login remote
      tags: execute
      ansible.posix.authorized_key:
        user: "{{ linux_user }}"
        state: present
        key: "{{ lookup('file','/tmp/remote-{{inventory_hostname}}-id_rsa.pub')}}"

    - name: Copy ssh-config to the webtop directory
      tags: execute
      ansible.builtin.copy:
        src: .ssh
        dest: webtop/
        remote_src: true
        mode: 0700

    - name: Create ssh config file
      tags: execute
      ansible.builtin.copy:
        dest: "webtop/.ssh/config"
        mode: 0600
        content: |
          Host localhost
            Hostname localhost
            User "{{ linux_user }}"
            StrictHostKeyChecking no

    - name: Run Webtop
      tags: execute
      become: true
      community.docker.docker_container:
        name: webtop
        image: lscr.io/linuxserver/webtop:fedora-xfce-2dcb9ef8-ls289
        state: started
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/Vienna"
          SUBFOLDER: "/"
          KEYBOARD: "de-de-qwertz"
          CUSTOM_PORT: "80"
          CUSTOM_HTTPS_PORT: "443"
        volumes:
          - /home/{{ linux_user }}/webtop:/config
          - /var/run/docker.sock:/var/run/docker.sock
          - /:/host
        security_opts:
          - "seccomp:unconfined"
        shm_size: 1G
        network_mode: host

    - name: Create desktop shortcut file explorer to home VM via sftp
      tags: execute
      ansible.builtin.copy:
        dest: "webtop/Desktop/home_vm.desktop"
        mode: '0755'
        content: |
          [Desktop Entry]
          Version=1.0
          Type=Application
          Name=Home VM
          Exec=thunar sftp://localhost/home/{{ linux_user }}
          Icon=go-home
          Path=
          Terminal=false
          StartupNotify=false

    - name: Create desktop shortcut terminal to VM
      tags: execute
      ansible.builtin.copy:
        dest: "webtop/Desktop/terminal_vm.desktop"
        mode: '0755'
        content: |
          [Desktop Entry]
          Version=1.0
          Type=Application
          Name=Terminal VM
          Exec=ssh -Y localhost
          Icon=utilities-terminal
          Path=
          Terminal=true
          StartupNotify=false

    - name: Create README
      tags: execute
      ansible.builtin.copy:
        dest: "webtop/Desktop/README.txt"
        mode: '0644'
        content: |
         Eigenheiten der Umgebung:
         Der Desktop läuft innerhalb eines Docker Containers in der VM

         Icons:
            "Home VM": Anzeigen des HOME-Verzeichnisses der VM
            "Terminal VM": SSH-Verbindung zur VM

##############################
### Start Workshop Inhalte ###
##############################

    - name: Clone OpenSpec Repo
      tags: execute
      ansible.builtin.git:
        repo: https://github.com/Gepardec/openspec-workshop.git
        dest: "{{ ansible_env.HOME }}/openspec-workshop"

    - name: Install NPM Dependencies
      tags: execute
      become: true
      ansible.builtin.command: npm install -g {{ item }}
      with_items:
        - pnpm
        - "@fission-ai/openspec@latest"

    - name: Install VS Code - RPM
      tags: execute
      become: true
      ansible.builtin.command: sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
    - name: Install VS Code - Repo
      become: true
      tags: execute
      ansible.builtin.copy:
        dest: "/etc/yum.repos.d/vscode.repo"
        mode: '0644'
        content: |
          [code]
          name=Visual Studio Code
          baseurl=https://packages.microsoft.com/yumrepos/vscode
          enabled=1
          autorefresh=1
          type=rpm-md
          gpgcheck=1
          gpgkey=https://packages.microsoft.com/keys/microsoft.asc
    - name: Install VS Code - Update
      tags: execute
      ignore_errors: true
      become: true
      ansible.builtin.command: sudo dnf check-update
    - name: Install VS Code
      tags: execute
      become: true
      ansible.builtin.command: sudo dnf install -y code

    - name: Install VS Code extensions
      tags: execute
      ansible.builtin.command: code --install-extension {{ item }} --force
      with_items:
        - angular.ng-template
        - openai.chatgpt
        - vscjava.vscode-java-debug
        - dbaeumer.vscode-eslint
        - vscjava.vscode-java-pack
        - redhat.java
        - vscjava.vscode-maven
        - esbenp.prettier-vscode
        - vscjava.vscode-java-dependency
        - redhat.vscode-quarkus
        - vscjava.vscode-java-test
        - vitest.explorer

    - name: Disable VS Code restricted mode
      tags: execute
      ansible.builtin.copy:
        dest: ".config/Code/User/settings.json"
        mode: '0644'
        content: |
          {
            "security.workspace.trust.enabled": false
          }

    - name: Create directories
      tags: execute
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - .codex

    - name: Add OpenAI Auth
      tags: execute
      ansible.builtin.template:
        src: files/auth.json
        dest: .codex/auth.json

    - name: Create desktop shortcut for VS Code to Workspace openspec-workshop
      tags: execute
      ansible.builtin.copy:
        dest: "webtop/Desktop/vscode.desktop"
        mode: '0755'
        content: |
          [Desktop Entry]
          Version=1.0
          Type=Application
          Name=VSCode
          Exec=ssh -Y localhost code openspec-workshop
          Icon=gtk-edit
          Path=
          Terminal=false
          StartupNotify=false

    - name: Install slides
      tags: execute
      ansible.builtin.command: pnpm install --dir openspec-workshop/slides/
