quarkus.datasource.db-kind=h2
quarkus.datasource.username=gepardec
quarkus.datasource.password=osw@gepardec
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

quarkus.rest.path=/api
quarkus.quinoa.enable-spa-routing=true
dashboard.spotlight.animal-id=6
